spring.application.name=Patient-service

server.error.include-binding-errors=always
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-exception=true

logging.level.root=INFO

server.port=4000
