spring.application.name=Patient-service

spring.web.error.include-binding-errors=always
spring.web.error.include-message=always
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=true

logging.level.root=INFO

server.port=4000

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer


